language: go

env:
  - GO111MODULE=on MONGO_URI="mongodb://localhost:27017" ES_URL="http://localhost:9200"

go:
  - 1.12.x

git:
  depth: 1

services: 
  - mongodb
  - elasticsearch

install: 
  - go mod init golang-crud-spa

script:
  - go build