version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    command: mongod --port 27017
    volumes:
    - .data/mongo:/data/db
    logging:
      driver: none
    ports:
    - 27017:27017
    networks:
      - custom-network
  
  backend:
    container_name: golang-backend
    build:
      context: .
      dockerfile: go.Dockerfile
    ports:
    - 8090:8090
    networks:
      - custom-network

  frontend:
    container_name: vue-frontend
    build:
      context: .
      dockerfile: vue.Dockerfile
    ports:
    - 8080:8080
    networks:
      - custom-network
   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    environment:
    - cluster.name=elastic
    - bootstrap.memory_lock=true
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks: 
      - custom-network

networks: 
  custom-network:
  