version: '3.3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    command: mongod --port 27018
    volumes:
    - .data/mongo:/data/db
    logging:
      driver: none
    ports:
    - 27018:27018
    networks:
      - custom-network
  
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8090:8090
    networks:
      - custom-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
    - node.name=es01
    - cluster.initial_master_nodes=es01
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200
    networks: 
      - custom-network

networks: 
  custom-network:
